### ISSUE TITLE
[개발환경] mysql 이미지 platform 제거

### ISSUE THREAD

**Issue by woogieReal** [woogieReal/MDGround3#146]
## AS-IS
``` yml
  mysql:
    container_name: MDGround3-db
    platform: linux/x86_64
    image: mysql:latest
    ....
```

## TO-BE
``` yml
  mysql:
    container_name: MDGround3-db
    image: mysql:latest
    ....
```
